---
- name: Force to accept RAs
  shell: echo 2 > /proc/sys/net/ipv6/conf/{{ BRIDGE_IF }}/accept_ra
  environment: "{{ he_cmd_lang }}"
  changed_when: True
- name: Parse libvirt default network configuration
  virt_net:
    command: get_xml
    name: default
  register: default_net_xml
- debug: var=default_net_xml.stdout
- name: Remove IPv4 configuration
  xml:
    xmlstring: "{{ default_net_xml.get_xml }}"
    xpath: /network/ip
    state: absent
  register: editednet_noipv4
- name: Edit libvirt default network configuration, 1
  xml:
    xmlstring: "{{ editednet_noipv4.xmlstring }}"
    xpath: /network/ip[@family='ipv6']
    attribute: address
    value: "{{ he_ipv6_subnet_prefix + '::1' }}"
  register: editednet1
- name: Edit libvirt default network configuration, 2
  xml:
    xmlstring: "{{ editednet1.xmlstring }}"
    xpath: /network/ip[@family='ipv6']
    attribute: prefix
    value: "64"
  register: editednet2
- debug: var=editednet2
- name: Edit libvirt default network configuration, 3
  xml:
    xmlstring: "{{ editednet2.xmlstring }}"
    xpath: /network/ip[@family='ipv6']/dhcp/range
    attribute: start
    value: "{{ he_ipv6_subnet_prefix + '::10' }}"
  register: editednet3
- debug: var=editednet3
- name: Edit libvirt default network configuration, 4
  xml:
    xmlstring: "{{ editednet3.xmlstring }}"
    xpath: /network/ip[@family='ipv6']/dhcp/range
    attribute: end
    value: "{{ he_ipv6_subnet_prefix + '::ff' }}"
  register: editednet4
- debug: var=editednet4
- name: Update libvirt default network configuration, 1
  virt_net:
    command: destroy
    name: default
- name: Update libvirt default network configuration, 2
  virt_net:
    command: undefine
    name: default
- name: Update libvirt default network configuration, 3
  virt_net:
    command: define
    name: default
    xml: "{{ editednet4.xmlstring }}"
- name: Activate default libvirt network
  virt_net:
    name: default
    state: active
  register: virt_net_out
